travis:
  secure:
    BINSTAR_TOKEN: J0CARfxGLS2UJv7sY3q2wHYF27rSnQrVg1MDHu1sF6TWQN8v00Wl0BTPb1AACx/uk51UaULK7kEhPDKGINlKlwA378sCKCraf2SormIT3xyr89/T/t4VqPRKP6F/Jv8Vt+zMWR+LxHTiDwYR/60UXPkEfGY2DZ0971bFJjhdymzjJ4U69w58n3uikg5I5ExaSw3XtMGzociYmhdr+CuA4NV+3B7ewRg7VHMQpNLVzpvOOPixoEBx0jjZ9/JqpZAoxCdzqzOD0XuvqO9/c/mBSb3SqZzsyhHM9XwTpihPvst8XpeNJGtAfHOBQoyrSdGnhSSUCwspStxgIR8EKe1/q9fXTdNp0FrvOndQu74EHdolX8w5RAmizTJWZ0s+lYfSGZ3SJoS5is9jRFDAHIC9C0sAsWPJEsO4hNy80ozUs2VQFrcboVhDzaI77F8R6irydMiqe/wAzCPMoNTG+Gp34dFJewcAxkoCFiSpLPzOySJ+QIfmsfPSr8BUDevEg85Njh6IyrvQYV2wHUyC+uq8OuL/s0tgtjoIt5UW0tv6ikO70bOuO4Xv0rn7hYHEOy3kjQgYLjxCM8SLMEeNOnZS1aREOgDjIk8Wi9NphPPjN3xMznm3QXVpDHpY7vpuK5+kDzx3C6uuhryl82wtOZosOpaWq9c6nVIp0+pI+iT1Zno=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
